project_id = "pazyddmjprfsloyuchnf"

[functions.process-bus-data]
verify_jwt = false

[functions.scrape-bus-schedules]
verify_jwt = false

[functions.test-scrape]
verify_jwt = false

[functions.process-all-lines]
verify_jwt = false