// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pazyddmjprfsloyuchnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhenlkZG1qcHJmc2xveXVjaG5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwOTMzODQsImV4cCI6MjA3MzY2OTM4NH0.E_x8n-p7h-J2oyMKeHm_qST4BBfayQr1KPGkvtrEsBk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});